spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: html
    encoding: utf-8
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:mysql://localhost:3306/sb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zxc12345
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 10000
    timeout: 5000